[project]
name = "w2d1-sql-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ljh", email = "1540696924@qq.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
w2d1-sql-basics = "w2d1_sql_basics:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
