[project]
name = "w1d5-fastapi-refactor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ljh", email = "1540696924@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
w1d5-fastapi-refactor = "w1d5_fastapi_refactor:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
