[project]
name = "w2d3-sqlalchemy-todo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ljh", email = "1540696924@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.5",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
w2d3-sqlalchemy-todo = "w2d3_sqlalchemy_todo:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
