[project]
name = "w1d3-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ljh", email = "1540696924@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
w1d3-check = "w1d3_check:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
